---
name: Docker build and deploy
on:
  push:
    branches:
      - main
      - develop
      - cicd/deepak
jobs:
  docker_build_push:
    runs-on: ubuntu-latest
    environment: cicd/deepak
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Docker build
        run: |
          echo "Building Docker images"
          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/dockerlab630 .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Images
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/dockerlab630
